
package org.mobileapi.server.entity;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "mobileAPI", targetNamespace = "http://mobileapi.org/wsdl", wsdlLocation = "file:/E:/MobileAPI/design/mobileapi.wsdl")
public class MobileAPI
    extends Service
{

    private final static URL MOBILEAPI_WSDL_LOCATION;
    private final static WebServiceException MOBILEAPI_EXCEPTION;
    private final static QName MOBILEAPI_QNAME = new QName("http://mobileapi.org/wsdl", "mobileAPI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/E:/MobileAPI/design/mobileapi.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MOBILEAPI_WSDL_LOCATION = url;
        MOBILEAPI_EXCEPTION = e;
    }

    public MobileAPI() {
        super(__getWsdlLocation(), MOBILEAPI_QNAME);
    }

    public MobileAPI(WebServiceFeature... features) {
        super(__getWsdlLocation(), MOBILEAPI_QNAME, features);
    }

    public MobileAPI(URL wsdlLocation) {
        super(wsdlLocation, MOBILEAPI_QNAME);
    }

    public MobileAPI(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MOBILEAPI_QNAME, features);
    }

    public MobileAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MobileAPI(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MobileAPIType
     */
    @WebEndpoint(name = "mobile")
    public MobileAPIType getMobile() {
        return super.getPort(new QName("http://mobileapi.org/wsdl", "mobile"), MobileAPIType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MobileAPIType
     */
    @WebEndpoint(name = "mobile")
    public MobileAPIType getMobile(WebServiceFeature... features) {
        return super.getPort(new QName("http://mobileapi.org/wsdl", "mobile"), MobileAPIType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MOBILEAPI_EXCEPTION!= null) {
            throw MOBILEAPI_EXCEPTION;
        }
        return MOBILEAPI_WSDL_LOCATION;
    }

}
