
package org.mobileapi.server.entity;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "mobileAPIType", targetNamespace = "http://mobileapi.org/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MobileAPIType {


    /**
     * 
     * @param request
     * @return
     *     returns org.mobileapi.server.entity.ReadUserResponse
     */
    @WebMethod(operationName = "ReadUser", action = "ReadUser")
    @WebResult(name = "ReadUserResponse", targetNamespace = "http://mobileapi.org", partName = "response")
    public ReadUserResponse readUser(
        @WebParam(name = "ReadUserRequest", targetNamespace = "http://mobileapi.org", partName = "request")
        ReadUserRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.mobileapi.server.entity.SaveUserResponse
     */
    @WebMethod(operationName = "SaveUser", action = "SaveUser")
    @WebResult(name = "SaveUserResponse", targetNamespace = "http://mobileapi.org", partName = "response")
    public SaveUserResponse saveUser(
        @WebParam(name = "SaveUserRequest", targetNamespace = "http://mobileapi.org", partName = "request")
        SaveUserRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.mobileapi.server.entity.ReadAppResponse
     */
    @WebMethod(operationName = "ReadApp", action = "ReadApp")
    @WebResult(name = "ReadAppResponse", targetNamespace = "http://mobileapi.org", partName = "response")
    public ReadAppResponse readApp(
        @WebParam(name = "ReadAppRequest", targetNamespace = "http://mobileapi.org", partName = "request")
        ReadAppRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.mobileapi.server.entity.SaveAppResponse
     */
    @WebMethod(operationName = "SaveApp", action = "SaveApp")
    @WebResult(name = "SaveAppResponse", targetNamespace = "http://mobileapi.org", partName = "response")
    public SaveAppResponse saveApp(
        @WebParam(name = "SaveAppRequest", targetNamespace = "http://mobileapi.org", partName = "request")
        SaveAppRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.mobileapi.server.entity.ListAppsResponse
     */
    @WebMethod(operationName = "ListApps", action = "ListApps")
    @WebResult(name = "ListAppsResponse", targetNamespace = "http://mobileapi.org", partName = "response")
    public ListAppsResponse listApps(
        @WebParam(name = "ListAppsRequest", targetNamespace = "http://mobileapi.org", partName = "request")
        ListAppsRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.mobileapi.server.entity.ReadDeviceResponse
     */
    @WebMethod(operationName = "ReadDevice", action = "ReadDevice")
    @WebResult(name = "ReadDeviceResponse", targetNamespace = "http://mobileapi.org", partName = "response")
    public ReadDeviceResponse readDevice(
        @WebParam(name = "ReadDeviceRequest", targetNamespace = "http://mobileapi.org", partName = "request")
        ReadDeviceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.mobileapi.server.entity.ListDevicesResponse
     */
    @WebMethod(operationName = "ListDevices", action = "ListDevices")
    @WebResult(name = "ListDevicesResponse", targetNamespace = "http://mobileapi.org", partName = "response")
    public ListDevicesResponse listDevices(
        @WebParam(name = "ListDevicesRequest", targetNamespace = "http://mobileapi.org", partName = "request")
        ListDevicesRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.mobileapi.server.entity.SaveDeviceResponse
     */
    @WebMethod(operationName = "SaveDevice", action = "SaveDevice")
    @WebResult(name = "SaveDeviceResponse", targetNamespace = "http://mobileapi.org", partName = "response")
    public SaveDeviceResponse saveDevice(
        @WebParam(name = "SaveDeviceRequest", targetNamespace = "http://mobileapi.org", partName = "request")
        SaveDeviceRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.mobileapi.server.entity.ReadChannelResponse
     */
    @WebMethod(operationName = "ReadChannel", action = "ReadChannel")
    @WebResult(name = "ReadChannelResponse", targetNamespace = "http://mobileapi.org", partName = "response")
    public ReadChannelResponse readChannel(
        @WebParam(name = "ReadChannelRequest", targetNamespace = "http://mobileapi.org", partName = "request")
        ReadChannelRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.mobileapi.server.entity.ListChannelsResponse
     */
    @WebMethod(operationName = "ListChannels", action = "ListChannels")
    @WebResult(name = "ListChannelsResponse", targetNamespace = "http://mobileapi.org", partName = "response")
    public ListChannelsResponse listChannels(
        @WebParam(name = "ListChannelsRequest", targetNamespace = "http://mobileapi.org", partName = "request")
        ListChannelsRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.mobileapi.server.entity.SaveChannelResponse
     */
    @WebMethod(operationName = "SaveChannel", action = "SaveChannel")
    @WebResult(name = "SaveChannelResponse", targetNamespace = "http://mobileapi.org", partName = "response")
    public SaveChannelResponse saveChannel(
        @WebParam(name = "SaveChannelRequest", targetNamespace = "http://mobileapi.org", partName = "request")
        SaveChannelRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.mobileapi.server.entity.RegisterUserResponse
     */
    @WebMethod(operationName = "RegisterUser", action = "RegisterUser")
    @WebResult(name = "RegisterUserResponse", targetNamespace = "http://mobileapi.org", partName = "response")
    public RegisterUserResponse registerUser(
        @WebParam(name = "RegisterUserRequest", targetNamespace = "http://mobileapi.org", partName = "request")
        RegisterUserRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.mobileapi.server.entity.ConfirmUserResponse
     */
    @WebMethod(operationName = "ConfirmUser", action = "ConfirmUser")
    @WebResult(name = "ConfirmUserResponse", targetNamespace = "http://mobileapi.org", partName = "response")
    public ConfirmUserResponse confirmUser(
        @WebParam(name = "ConfirmUserRequest", targetNamespace = "http://mobileapi.org", partName = "request")
        ConfirmUserRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.mobileapi.server.entity.InitPwdUserResponse
     */
    @WebMethod(operationName = "InitPwdUser", action = "InitPwdUser")
    @WebResult(name = "InitPwdUserResponse", targetNamespace = "http://mobileapi.org", partName = "response")
    public InitPwdUserResponse initPwdUser(
        @WebParam(name = "InitPwdUserRequest", targetNamespace = "http://mobileapi.org", partName = "request")
        InitPwdUserRequest request);

    /**
     * 
     * @param request
     * @return
     *     returns org.mobileapi.server.entity.LogonResponse
     */
    @WebMethod(operationName = "Logon", action = "Logon")
    @WebResult(name = "LogonResponse", targetNamespace = "http://mobileapi.org", partName = "response")
    public LogonResponse logon(
        @WebParam(name = "LogonRequest", targetNamespace = "http://mobileapi.org", partName = "request")
        LogonRequest request);

}
